### ISSUE TITLE
Missing disabled state for past tasks in ListView

### ISSUE THREAD

**Issue by Prokyonn** [sulu/SuluAutomationBundle#28]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Bundle Version | Specific version or SHA of a commit
| Sulu Version | 2.0
| Browser Version | Browser name and version

#### Actual Behavior

Currently AutomationTasks from the past are not disabled in the list and can still be edited.

#### Expected Behavior

Past tasks should be disabled and not editable.

**Comment by alexander-schranz** [comment]
Tested on https://sulu.rocks they are not longer edit or selectable.
