### ISSUE TITLE
Missing Save-Button Task Information

### ISSUE THREAD

**Issue by Prokyonn** [sulu/SuluAutomationBundle#30]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Bundle Version | for 2.0
| Sulu Version | 2.0
| Browser Version | Browser name and version

#### Actual Behavior

The information about the currently active task is missing.

#### Expected Behavior

If a task is active for a page, the save button should have a small information about the date and action of the currently active task.

**Comment by alexander-schranz** [comment]
@chirimoya @danrot Do we see this as a requirement for the 2.0 release?

**Comment by chirimoya** [comment]
Not required for me.

**Comment by niklasnatter** [comment]
Closing this as a non-requirement 😇
