### ISSUE TITLE
Add translations to crowdin

### ISSUE THREAD

**Issue by kleinkoerkamp** [sulu/SuluAutomationBundle#32]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | develop
| Sulu Version | 2.0.3

#### Actual Behavior

So that it's translatable

**Comment by danrot** [comment]
Will be fixed in #33, added already existing translations to crowdin, however, two of them were missing.

**Comment by danrot** [comment]
Fixed in #33
