### ISSUE TITLE
Return value must be of type Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata\SchemaMetadata, null returned

### ISSUE THREAD

**Issue by NeuralClone** [sulu/SuluAutomationBundle#73]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 2.1.2
| Sulu Version | 2.6.3
| PHP Version | 8.3.8
| Browser Version | --

### Actual Behavior

When attempting to add a new automation task (e.g., unpublish a page), a PHP type error occurs:

```
TypeError:
Sulu\Bundle\AdminBundle\Metadata\FormMetadata\FormMetadata::getSchema():
Return value must be of type Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata\SchemaMetadata, null returned

  at vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php:116
  at Sulu\Bundle\AdminBundle\Metadata\FormMetadata\FormMetadata->getSchema()
     (vendor/sulu/sulu/src/Sulu/Component/Content/Types/Metadata/GlobalBlocksTypedFormMetadataVisitor.php:108)
  at Sulu\Component\Content\Types\Metadata\GlobalBlocksTypedFormMetadataVisitor->visitFormMetadata()
     (vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php:74)
  at Sulu\Bundle\AdminBundle\Metadata\FormMetadata\FormMetadataProvider->getMetadata()
     (vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Controller/AdminController.php:197)
  at Sulu\Bundle\AdminBundle\Controller\AdminController->metadataAction()
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:69)  
```

While debugging this, the `FormMetadata::$schema` property is indeed null when the metadata for `task_details` is retrieved. But this property can't be null: [FormMetadata.php#L43-L44](https://github.com/sulu/sulu/blob/a050778ef46a2e910822d25d1b8a263a14e79085/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php#L43-L44), [FormMetadata.php#L43-L44](https://github.com/sulu/sulu/blob/a050778ef46a2e910822d25d1b8a263a14e79085/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php#L43-L44).

### Expected Behavior

It should be possible to add a task without the Sulu admin crashing.

### Steps to Reproduce

1. Create a project based on `sulu/skeleton`.
2. Install this bundle.
3. Edit the default homepage > go to the Automation tab > click the Add button to schedule the default page to be unpublished.

You can also access the `/admin/metadata/form/task_details?entityClass=Sulu\Bundle\PageBundle\Document\BasePageDocument` URI directly from the Sulu admin to trigger the error.

### Possible Solutions

The source of the problem is in `FormMetadataLoader` when the `task_details` form metadata is built:

https://github.com/sulu/SuluAutomationBundle/blob/629e540e6622eeafb163a124292af9b773958cec/Metadata/FormMetadataLoader.php#L51-L60

The `$schema` property is never set to a valid object and that triggers a PHP type error. The now [deprecated version](https://github.com/sulu/sulu/blob/a050778ef46a2e910822d25d1b8a263a14e79085/src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadata.php) of `FormMetadata` allowed for this particular property to be null. So, this is probably just a holdover from that.

I'm not sure what the form's `SchemaMetadata` is supposed to be set to. But since it doesn't appear to be set to anything in the existing code, perhaps simply initializing it to an empty object would suffice?

```php
$form->setSchema(new SchemaMetadata());
```

This simple addition seems to fully resolve the issue for me.

**Comment by alexander-schranz** [comment]
Looks for me like an issue in the new added `GlobalBlocksTypedFormMetadataVisitor` trigger this error now, think nullability was may just forgotten to add to the phpdoc type but having always a Schema would be better for the developer experience. So I think `$form->setSchema(new SchemaMetadata());` will not hurt and be better.

Do you want to create a pull request for it?

**Comment by NeuralClone** [comment]
Sure! I'd be happy to.
