### ISSUE TITLE
SuluAutomationBundle's main.js is not loaded due to wrong path

### ISSUE THREAD

**Issue by chebotaryov** [sulu/SuluAutomationBundle#9]
Admin is not loaded proprely. When SuluAutomationBundle is registered its main.js is not loaded due to wrong path:
```
An Exception was thrown while handling: No route found for "GET /ru/bundles/suluautomation/js/main.js"
 (from "http://etp.reliz/admin/")
```

For webspace I set routes depending on localization:
```
 <portals>
        <portal>
            <name>example.com</name>
            <key>example</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
```

**Comment by wachterjohannes** [comment]
@chebotaryov after installing the bundle has you called `bin/console assets:install` this looks like the public files wasnt linked to web folder

**Comment by chebotaryov** [comment]
@wachterjohannes I did this. main.js file was copied to /web/bundles/suluautomation/ directory but issue still remains unresolved:
![image](https://cloud.githubusercontent.com/assets/4707338/23704520/6c7bb5aa-0416-11e7-8935-aee2a40a4dae.png)

**Comment by wachterjohannes** [comment]
the redirect to the locale will be done in sulu - so the webserver could not find the file. Maybe the redirect was cached in the browser? could you clear the local cache?

**Comment by chebotaryov** [comment]
Thanks. Issue was resolved

**Comment by wachterjohannes** [comment]
no problem (:
